// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmeNr4DYI678-dvAJtrOd0I8zQyd-GRcc',
    appId: '1:425253324637:web:8bf59dd374e0f146180ab4',
    messagingSenderId: '425253324637',
    projectId: 'social-app-f8ffa',
    authDomain: 'social-app-f8ffa.firebaseapp.com',
    storageBucket: 'social-app-f8ffa.appspot.com',
    measurementId: 'G-XG7ZJ7E9H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaQbTyqFkWqxH40sSEwsJZudK2W3nnMNg',
    appId: '1:425253324637:android:b1384d535cb36f87180ab4',
    messagingSenderId: '425253324637',
    projectId: 'social-app-f8ffa',
    storageBucket: 'social-app-f8ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kQzkQ1HQpAT73NKKRKpm45f10-Dyoyk',
    appId: '1:425253324637:ios:48e64772cce09a00180ab4',
    messagingSenderId: '425253324637',
    projectId: 'social-app-f8ffa',
    storageBucket: 'social-app-f8ffa.appspot.com',
    iosClientId: '425253324637-62tn8jn2argl46j08tv543glbp4o1a48.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kQzkQ1HQpAT73NKKRKpm45f10-Dyoyk',
    appId: '1:425253324637:ios:48e64772cce09a00180ab4',
    messagingSenderId: '425253324637',
    projectId: 'social-app-f8ffa',
    storageBucket: 'social-app-f8ffa.appspot.com',
    iosClientId: '425253324637-62tn8jn2argl46j08tv543glbp4o1a48.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
